version: 2.1

orbs:
  node: circleci/node@4.9.0
  aws-cli: circleci/aws-cli@1.3.1
  eb: circleci/aws-elastic-beanstalk@2.0.1
  browser-tools: circleci/browser-tools@1.2.3

executors:
  docker-node-awscli:
    docker:
      - image: cimg/base:stable

jobs:
  install-frontend:
    executor: docker-node-awscli
    working_directory: ~/udagram
    steps:
      - node/install
      - checkout
      - run:
          name: Front-End Install
          command: npm run frontend:install
      - persist_to_workspace:
          root: ~/udagram
          paths:
            - ./

  test-frontend:
    docker:
      - image: 'cimg/node:14.18.0-browsers'
    working_directory: ~/udagram
    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - attach_workspace:
          at: ~/udagram
      - run:
          name: Front-End Test
          command: npm run frontend:test

  build-and-deploy-frontend-prod:
    executor: docker-node-awscli
    working_directory: ~/udagram
    steps:
      - node/install
      - aws-cli/setup
      - attach_workspace:
          at: ~/udagram
      - run:
          name: Front-End Build Prod
          command: |
            export NODE_OPTIONS=--openssl-legacy-provider && npm run frontend:build:prod
      - run:
          name: Deploy App Prod
          command: |
            npm run frontend:deploy:prod

  build-and-deploy-frontend-stg:
    executor: docker-node-awscli
    working_directory: ~/udagram
    steps:
      - node/install
      - aws-cli/setup
      - attach_workspace:
          at: ~/udagram
      - run:
          name: Front-End Build Staging
          command: |
            export NODE_OPTIONS=--openssl-legacy-provider && npm run frontend:build:stg
      - run:
          name: Deploy App Staging
          command: |
            npm run frontend:deploy:stg

  install-backend:
    executor: docker-node-awscli
    working_directory: ~/udagram
    steps:
      - node/install
      - checkout
      - run:
          name: Back-End Install
          command: npm run backend:install
      - persist_to_workspace:
          root: ~/udagram
          paths:
            - ./

  test-backend:
    executor: docker-node-awscli
    working_directory: ~/udagram
    steps:
      - node/install
      - attach_workspace:
          at: ~/udagram
      - run:
          name: Back-End Test
          command: npm run backend:test

  build-and-deploy-backend-prod:
    executor: docker-node-awscli
    working_directory: ~/udagram
    steps:
      - node/install
      - aws-cli/setup
      - eb/setup
      - attach_workspace:
          at: ~/udagram
      - run:
          name: Back-End Build Prod
          command: |
            npm run backend:build
      - run:
          name: Deploy App Prod
          command: |
            cd ~/udagram/udagram-api/www
            eb init $APPLICATION_NAME -r $AWS_DEFAULT_REGION -p $EB_PLATFORM
            eb use $EB_ENV_NAME_PROD
            eb setenv ENV=$PROD_ENV \
              POSTGRES_HOST=$PROD_POSTGRES_HOST \
              POSTGRES_DB=$PROD_POSTGRES_DB \
              POSTGRES_USERNAME=$PROD_POSTGRES_USERNAME \
              POSTGRES_PASSWORD=$PROD_POSTGRES_PASSWORD \
              POSTGRES_PORT=$PROD_POSTGRES_PORT \
              AWS_BUCKET=$PROD_AWS_BUCKET \
              AWS_ACCESS_KEY_ID=$PROD_AWS_ACCESS_KEY_ID \
              AWS_SECRET_ACCESS_KEY=$PROD_AWS_SECRET_ACCESS_KEY \
              AWS_REGION=$PROD_AWS_REGION \
              JWT_SECRET=$PROD_JWT_SECRET \
              URL=$PROD_URL \
              PORT=$PROD_PORT
            eb deploy $EB_ENV_NAME_PROD
            eb status $EB_ENV_NAME_PROD

  build-and-deploy-backend-stg:
    executor: docker-node-awscli
    working_directory: ~/udagram
    steps:
      - node/install
      - aws-cli/setup
      - eb/setup
      - attach_workspace:
          at: ~/udagram
      - run:
          name: Back-End Build Staging
          command: |
            npm run backend:build
      - run:
          name: Deploy App Staging
          command: |
            cd ~/udagram/udagram-api/www
            eb init $APPLICATION_NAME -r $AWS_DEFAULT_REGION -p $EB_PLATFORM
            eb use $EB_ENV_NAME_STG
            eb setenv ENV=$STG_ENV \
              POSTGRES_HOST=$STG_POSTGRES_HOST \
              POSTGRES_DB=$STG_POSTGRES_DB \
              POSTGRES_USERNAME=$STG_POSTGRES_USERNAME \
              POSTGRES_PASSWORD=$STG_POSTGRES_PASSWORD \
              POSTGRES_PORT=$STG_POSTGRES_PORT \
              AWS_BUCKET=$STG_AWS_BUCKET \
              AWS_ACCESS_KEY_ID=$STG_AWS_ACCESS_KEY_ID \
              AWS_SECRET_ACCESS_KEY=$STG_AWS_SECRET_ACCESS_KEY \
              AWS_REGION=$STG_AWS_REGION \
              JWT_SECRET=$STG_JWT_SECRET \
              URL=$STG_URL \
              PORT=$STG_PORT
            eb deploy $EB_ENV_NAME_STG
            eb status $EB_ENV_NAME_STG


workflows:
  version: 2
  test-and-deploy-stg:
    jobs:
      - install-backend:
          filters:
            branches:
              ignore:
                - main
      - install-frontend:
          filters:
            branches:
              ignore:
                - main
      - test-backend:
          requires:
            - install-backend
          filters:
            branches:
              ignore:
                - main
      - test-frontend:
          requires:
            - install-frontend
          filters:
            branches:
              ignore:
                - main
      - build-and-deploy-backend-stg:
          requires:
            - test-backend
          filters:
            branches:
              ignore:
                - main
      - build-and-deploy-frontend-stg:
          requires:
            - test-frontend
          filters:
            branches:
              ignore:
                - main

  deploy-prod:
    jobs:
      - install-backend:
          filters:
            branches:
              only:
                - main
      - install-frontend:
          filters:
            branches:
              only:
                - main
      - build-and-deploy-backend-prod:
          requires:
            - install-backend
          filters:
            branches:
              only:
                - main
      - build-and-deploy-frontend-prod:
          requires:
            - install-frontend
          filters:
            branches:
              only:
                - main
